version: '3.8'
services:
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # container_name: portfolio-dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    stdin_open: true
    tty: true